### PR TITLE
Themed status bar and toolbar

### PR DESCRIPTION
**Pull request by astares**
- allow statusbar also to be themed
 - use the window color as color for toolbar to follow other UI frameworks

### CODE REVIEW

**Comment by dionisiydk** [comment]
Cool! First contribution. 
Thank's

**Comment by astares** [comment]
calypso

**Comment by dionisiydk** [comment]
Hi Torsten.
As I understand the main idea is that browser should just follow the theme.
And current theme extensions which I introduced break this rule.
And your change fix it by #windowColor in these extensions. 
Should we just use #windowColor instead of calypsoStatusBarColor and calypsoToolbarColor?
It will simplify browser. Generally I prefer to not extend themes.
What you think?

**Comment by astares** [comment]
Fine for me. It is very unusual that someone themes the status bar and toolbar different.

**Comment by dionisiydk** [comment]
Ok. It's done.
But it is still not a time for release.
Anyway now I need to be used to it.

**Pull request merged**
